max_width = 120        # 每行最大长度
hard_tabs = false   # 是否使用 Tab 键缩进
tab_spaces = 4      # Tab 键等于多少个空格
newline_style = "Auto"  # 换行符风格，Auto、Unix、Windows
use_small_heuristics = "Default"  # 使用小型启发式算法，Default、Off、Max
reorder_imports = true  # 是否对 use 语句排序
reorder_modules = true  # 是否对 mod 语句排序
remove_nested_parens = true  # 是否移除嵌套的括号
fn_brace_style = "SameLineWhere"  # 函数大括号风格，SameLineWhere、AlwaysNextLine
item_brace_style = "SameLineWhere" # 项目大括号风格，SameLineWhere、AlwaysNextLine
struct_lit_style = "Block"  # 结构体字面量风格，Block、Compressed
trailing_comma = "Vertical"  # 逗号风格，Vertical、Horizontal、Never
format_strings = false # 是否格式化字符串
wrap_comments = true  # 是否换行注释
generics_indent = "Vertical"  # 泛型缩进风格，Vertical、Block
where_layout = "Vertical"  # where 子句布局，Vertical、Horizontal、Mixed
# edition = "2021"  # Rust 版本
merge_derives = true  # 是否合并相同的 derive 属性
# use_try_shorthand = false # 是否使用 ? 语法糖
use_field_init_shorthand = false  # 是否使用字段初始化简写
force_explicit_abi = true  # 是否强制使用显式 ABI